#!/bin/bash

set -e

if [[ -e /etc/profile ]]; then
	source /etc/profile
fi

# some platforms don't have a realpath binary
cwd=$(perl -e 'use Cwd "abs_path";print abs_path(shift)' $0/..)

CLASSPATH="$(echo ${cwd}/target/camus-*-SNAPSHOT-shaded.jar):$(hadoop classpath)"
exec /usr/bin/java -cp $CLASSPATH com.linkedin.camus.etl.kafka.CamusJob -P ${cwd}/camus.properties "$@"
