/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.linkedin.camus.events;

@SuppressWarnings("all")
@org.apache.avro.specific.FixedSize(16)
public class Guid extends org.apache.avro.specific.SpecificFixed {
}