/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.linkedin.camus.events.records;  
@SuppressWarnings("all")
/** The basic header for every tracking event. */
public class EventHeader extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"EventHeader\",\"namespace\":\"com.linkedin.camus.events.records\",\"doc\":\"The basic header for every tracking event.\",\"fields\":[{\"name\":\"memberId\",\"type\":\"int\",\"doc\":\"The member id of the user initiating the action\"},{\"name\":\"time\",\"type\":\"long\",\"doc\":\"The time of the event\"},{\"name\":\"server\",\"type\":\"string\",\"doc\":\"The name of the server\"},{\"name\":\"service\",\"type\":\"string\",\"doc\":\"The name of the service\"},{\"name\":\"guid\",\"type\":{\"type\":\"fixed\",\"name\":\"Guid\",\"size\":16},\"doc\":\"A unique identifier for the message\"},{\"name\":\"treeId\",\"type\":[\"null\",{\"type\":\"fixed\",\"name\":\"fixed_16\",\"size\":16}],\"doc\":\"Service call tree uuid\",\"default\":null},{\"name\":\"requestId\",\"type\":[\"null\",\"int\"],\"doc\":\"Service call request id\",\"default\":null},{\"name\":\"impersonatorId\",\"type\":[\"null\",\"string\"],\"doc\":\"this is the ID of the CS Agent or Application acting on the users behalf\",\"default\":null}]}");
  /** The member id of the user initiating the action */
  @Deprecated public int memberId;
  /** The time of the event */
  @Deprecated public long time;
  /** The name of the server */
  @Deprecated public java.lang.CharSequence server;
  /** The name of the service */
  @Deprecated public java.lang.CharSequence service;
  /** A unique identifier for the message */
  @Deprecated public com.linkedin.camus.events.records.Guid guid;
  /** Service call tree uuid */
  @Deprecated public com.linkedin.camus.events.records.fixed_16 treeId;
  /** Service call request id */
  @Deprecated public java.lang.Integer requestId;
  /** this is the ID of the CS Agent or Application acting on the users behalf */
  @Deprecated public java.lang.CharSequence impersonatorId;
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return memberId;
    case 1: return time;
    case 2: return server;
    case 3: return service;
    case 4: return guid;
    case 5: return treeId;
    case 6: return requestId;
    case 7: return impersonatorId;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: memberId = (java.lang.Integer)value$; break;
    case 1: time = (java.lang.Long)value$; break;
    case 2: server = (java.lang.CharSequence)value$; break;
    case 3: service = (java.lang.CharSequence)value$; break;
    case 4: guid = (com.linkedin.camus.events.records.Guid)value$; break;
    case 5: treeId = (com.linkedin.camus.events.records.fixed_16)value$; break;
    case 6: requestId = (java.lang.Integer)value$; break;
    case 7: impersonatorId = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'memberId' field.
   * The member id of the user initiating the action   */
  public java.lang.Integer getMemberId() {
    return memberId;
  }

  /**
   * Sets the value of the 'memberId' field.
   * The member id of the user initiating the action   * @param value the value to set.
   */
  public void setMemberId(java.lang.Integer value) {
    this.memberId = value;
  }

  /**
   * Gets the value of the 'time' field.
   * The time of the event   */
  public java.lang.Long getTime() {
    return time;
  }

  /**
   * Sets the value of the 'time' field.
   * The time of the event   * @param value the value to set.
   */
  public void setTime(java.lang.Long value) {
    this.time = value;
  }

  /**
   * Gets the value of the 'server' field.
   * The name of the server   */
  public java.lang.CharSequence getServer() {
    return server;
  }

  /**
   * Sets the value of the 'server' field.
   * The name of the server   * @param value the value to set.
   */
  public void setServer(java.lang.CharSequence value) {
    this.server = value;
  }

  /**
   * Gets the value of the 'service' field.
   * The name of the service   */
  public java.lang.CharSequence getService() {
    return service;
  }

  /**
   * Sets the value of the 'service' field.
   * The name of the service   * @param value the value to set.
   */
  public void setService(java.lang.CharSequence value) {
    this.service = value;
  }

  /**
   * Gets the value of the 'guid' field.
   * A unique identifier for the message   */
  public com.linkedin.camus.events.records.Guid getGuid() {
    return guid;
  }

  /**
   * Sets the value of the 'guid' field.
   * A unique identifier for the message   * @param value the value to set.
   */
  public void setGuid(com.linkedin.camus.events.records.Guid value) {
    this.guid = value;
  }

  /**
   * Gets the value of the 'treeId' field.
   * Service call tree uuid   */
  public com.linkedin.camus.events.records.fixed_16 getTreeId() {
    return treeId;
  }

  /**
   * Sets the value of the 'treeId' field.
   * Service call tree uuid   * @param value the value to set.
   */
  public void setTreeId(com.linkedin.camus.events.records.fixed_16 value) {
    this.treeId = value;
  }

  /**
   * Gets the value of the 'requestId' field.
   * Service call request id   */
  public java.lang.Integer getRequestId() {
    return requestId;
  }

  /**
   * Sets the value of the 'requestId' field.
   * Service call request id   * @param value the value to set.
   */
  public void setRequestId(java.lang.Integer value) {
    this.requestId = value;
  }

  /**
   * Gets the value of the 'impersonatorId' field.
   * this is the ID of the CS Agent or Application acting on the users behalf   */
  public java.lang.CharSequence getImpersonatorId() {
    return impersonatorId;
  }

  /**
   * Sets the value of the 'impersonatorId' field.
   * this is the ID of the CS Agent or Application acting on the users behalf   * @param value the value to set.
   */
  public void setImpersonatorId(java.lang.CharSequence value) {
    this.impersonatorId = value;
  }

  /** Creates a new EventHeader RecordBuilder */
  public static com.linkedin.camus.events.records.EventHeader.Builder newBuilder() {
    return new com.linkedin.camus.events.records.EventHeader.Builder();
  }
  
  /** Creates a new EventHeader RecordBuilder by copying an existing Builder */
  public static com.linkedin.camus.events.records.EventHeader.Builder newBuilder(com.linkedin.camus.events.records.EventHeader.Builder other) {
    return new com.linkedin.camus.events.records.EventHeader.Builder(other);
  }
  
  /** Creates a new EventHeader RecordBuilder by copying an existing EventHeader instance */
  public static com.linkedin.camus.events.records.EventHeader.Builder newBuilder(com.linkedin.camus.events.records.EventHeader other) {
    return new com.linkedin.camus.events.records.EventHeader.Builder(other);
  }
  
  /**
   * RecordBuilder for EventHeader instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<EventHeader>
    implements org.apache.avro.data.RecordBuilder<EventHeader> {

    private int memberId;
    private long time;
    private java.lang.CharSequence server;
    private java.lang.CharSequence service;
    private com.linkedin.camus.events.records.Guid guid;
    private com.linkedin.camus.events.records.fixed_16 treeId;
    private java.lang.Integer requestId;
    private java.lang.CharSequence impersonatorId;

    /** Creates a new Builder */
    private Builder() {
      super(com.linkedin.camus.events.records.EventHeader.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(com.linkedin.camus.events.records.EventHeader.Builder other) {
      super(other);
    }
    
    /** Creates a Builder by copying an existing EventHeader instance */
    private Builder(com.linkedin.camus.events.records.EventHeader other) {
            super(com.linkedin.camus.events.records.EventHeader.SCHEMA$);
      if (isValidValue(fields()[0], other.memberId)) {
        this.memberId = (java.lang.Integer) data().deepCopy(fields()[0].schema(), other.memberId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.time)) {
        this.time = (java.lang.Long) data().deepCopy(fields()[1].schema(), other.time);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.server)) {
        this.server = (java.lang.CharSequence) data().deepCopy(fields()[2].schema(), other.server);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.service)) {
        this.service = (java.lang.CharSequence) data().deepCopy(fields()[3].schema(), other.service);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.guid)) {
        this.guid = (com.linkedin.camus.events.records.Guid) data().deepCopy(fields()[4].schema(), other.guid);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.treeId)) {
        this.treeId = (com.linkedin.camus.events.records.fixed_16) data().deepCopy(fields()[5].schema(), other.treeId);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.requestId)) {
        this.requestId = (java.lang.Integer) data().deepCopy(fields()[6].schema(), other.requestId);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.impersonatorId)) {
        this.impersonatorId = (java.lang.CharSequence) data().deepCopy(fields()[7].schema(), other.impersonatorId);
        fieldSetFlags()[7] = true;
      }
    }

    /** Gets the value of the 'memberId' field */
    public java.lang.Integer getMemberId() {
      return memberId;
    }
    
    /** Sets the value of the 'memberId' field */
    public com.linkedin.camus.events.records.EventHeader.Builder setMemberId(int value) {
      validate(fields()[0], value);
      this.memberId = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'memberId' field has been set */
    public boolean hasMemberId() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'memberId' field */
    public com.linkedin.camus.events.records.EventHeader.Builder clearMemberId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'time' field */
    public java.lang.Long getTime() {
      return time;
    }
    
    /** Sets the value of the 'time' field */
    public com.linkedin.camus.events.records.EventHeader.Builder setTime(long value) {
      validate(fields()[1], value);
      this.time = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'time' field has been set */
    public boolean hasTime() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'time' field */
    public com.linkedin.camus.events.records.EventHeader.Builder clearTime() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'server' field */
    public java.lang.CharSequence getServer() {
      return server;
    }
    
    /** Sets the value of the 'server' field */
    public com.linkedin.camus.events.records.EventHeader.Builder setServer(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.server = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'server' field has been set */
    public boolean hasServer() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'server' field */
    public com.linkedin.camus.events.records.EventHeader.Builder clearServer() {
      server = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'service' field */
    public java.lang.CharSequence getService() {
      return service;
    }
    
    /** Sets the value of the 'service' field */
    public com.linkedin.camus.events.records.EventHeader.Builder setService(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.service = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'service' field has been set */
    public boolean hasService() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'service' field */
    public com.linkedin.camus.events.records.EventHeader.Builder clearService() {
      service = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'guid' field */
    public com.linkedin.camus.events.records.Guid getGuid() {
      return guid;
    }
    
    /** Sets the value of the 'guid' field */
    public com.linkedin.camus.events.records.EventHeader.Builder setGuid(com.linkedin.camus.events.records.Guid value) {
      validate(fields()[4], value);
      this.guid = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'guid' field has been set */
    public boolean hasGuid() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'guid' field */
    public com.linkedin.camus.events.records.EventHeader.Builder clearGuid() {
      guid = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the 'treeId' field */
    public com.linkedin.camus.events.records.fixed_16 getTreeId() {
      return treeId;
    }
    
    /** Sets the value of the 'treeId' field */
    public com.linkedin.camus.events.records.EventHeader.Builder setTreeId(com.linkedin.camus.events.records.fixed_16 value) {
      validate(fields()[5], value);
      this.treeId = value;
      fieldSetFlags()[5] = true;
      return this; 
    }
    
    /** Checks whether the 'treeId' field has been set */
    public boolean hasTreeId() {
      return fieldSetFlags()[5];
    }
    
    /** Clears the value of the 'treeId' field */
    public com.linkedin.camus.events.records.EventHeader.Builder clearTreeId() {
      treeId = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /** Gets the value of the 'requestId' field */
    public java.lang.Integer getRequestId() {
      return requestId;
    }
    
    /** Sets the value of the 'requestId' field */
    public com.linkedin.camus.events.records.EventHeader.Builder setRequestId(java.lang.Integer value) {
      validate(fields()[6], value);
      this.requestId = value;
      fieldSetFlags()[6] = true;
      return this; 
    }
    
    /** Checks whether the 'requestId' field has been set */
    public boolean hasRequestId() {
      return fieldSetFlags()[6];
    }
    
    /** Clears the value of the 'requestId' field */
    public com.linkedin.camus.events.records.EventHeader.Builder clearRequestId() {
      requestId = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /** Gets the value of the 'impersonatorId' field */
    public java.lang.CharSequence getImpersonatorId() {
      return impersonatorId;
    }
    
    /** Sets the value of the 'impersonatorId' field */
    public com.linkedin.camus.events.records.EventHeader.Builder setImpersonatorId(java.lang.CharSequence value) {
      validate(fields()[7], value);
      this.impersonatorId = value;
      fieldSetFlags()[7] = true;
      return this; 
    }
    
    /** Checks whether the 'impersonatorId' field has been set */
    public boolean hasImpersonatorId() {
      return fieldSetFlags()[7];
    }
    
    /** Clears the value of the 'impersonatorId' field */
    public com.linkedin.camus.events.records.EventHeader.Builder clearImpersonatorId() {
      impersonatorId = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    @Override
    public EventHeader build() {
      try {
        EventHeader record = new EventHeader();
        record.memberId = fieldSetFlags()[0] ? this.memberId : (java.lang.Integer) defaultValue(fields()[0]);
        record.time = fieldSetFlags()[1] ? this.time : (java.lang.Long) defaultValue(fields()[1]);
        record.server = fieldSetFlags()[2] ? this.server : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.service = fieldSetFlags()[3] ? this.service : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.guid = fieldSetFlags()[4] ? this.guid : (com.linkedin.camus.events.records.Guid) defaultValue(fields()[4]);
        record.treeId = fieldSetFlags()[5] ? this.treeId : (com.linkedin.camus.events.records.fixed_16) defaultValue(fields()[5]);
        record.requestId = fieldSetFlags()[6] ? this.requestId : (java.lang.Integer) defaultValue(fields()[6]);
        record.impersonatorId = fieldSetFlags()[7] ? this.impersonatorId : (java.lang.CharSequence) defaultValue(fields()[7]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
