/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.linkedin.camus.events.records;  
@SuppressWarnings("all")
@org.apache.avro.specific.FixedSize(16)
public class fixed_16 extends org.apache.avro.specific.SpecificFixed {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"fixed\",\"name\":\"fixed_16\",\"namespace\":\"com.linkedin.camus.events.records\",\"size\":16}");
  
  /** Creates a new fixed_16 */
  public fixed_16() {
    super();
  }
  
  /** Creates a new fixed_16 with the given bytes */
  public fixed_16(byte[] bytes) {
    super(bytes);
  }
}
