/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.linkedin.camus.events.records;  
@SuppressWarnings("all")
@org.apache.avro.specific.FixedSize(16)
public class Guid extends org.apache.avro.specific.SpecificFixed {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"fixed\",\"name\":\"Guid\",\"namespace\":\"com.linkedin.camus.events.records\",\"size\":16}");
  
  /** Creates a new Guid */
  public Guid() {
    super();
  }
  
  /** Creates a new Guid with the given bytes */
  public Guid(byte[] bytes) {
    super(bytes);
  }
}
