#!/bin/bash
set -e
mkdir -p .venv
test -e .venv/bin/activate || virtualenv .venv --no-site-packages
. .venv/bin/activate
pip install azkaban==0.7.0
bundle install
bundle exec ejson decrypt camus-shopify/azkaban.ejson > camus-shopify/azkaban.json
