#!/usr/bin/env python
import os
import sys
import json
import argparse
import subprocess
import logging as lg
from os.path import basename, exists

from azkaban import Job, Project
from azkaban.remote import Session


formatter = lg.Formatter('%(asctime)s %(levelname)s %(name)s %(message)s', '%d/%m/%y %H:%M:%S')
ch = lg.StreamHandler(sys.stdout)
ch.setFormatter(formatter)
logger = lg.getLogger('azkaban_submit_job')
logger.setLevel(lg.INFO)
logger.addHandler(ch)

def start_session(url, username, password):
    session = Session(url)
    session.user = username
    session.password = password
    session.id = None
    return session

def get_camus_version(path):
    path = os.path.join(path, 'camus-shopify')
    logger.info('Retrieving Camus version from %s' % path)
    cmd = "mvn org.apache.maven.plugins:maven-help-plugin:2.1.1:evaluate -Dexpression=project.version | grep -Ev '(^\[|Download\w+:)'"
    return run_shell_command(cmd, 'Retrieved Camus version', path, True)

def main():
    repo_root = os.getcwd()
    camus_jar = get_camus_version(repo_root)
    azkaban_auth = json.load(open(os.path.join(repo_root, 'camus-shopify', 'azkaban.json')))

    command =  'sudo -E -u deploy '
    command += 'bash -c "java -Xms1G -Xmx1G -DHADOOP_USER_NAME=deploy '
    command += '-Dlog4j.configuration=file:/u/apps/camus/shared/log4j.xml '
    command += '-cp $(hadoop classpath):/u/apps/camus/current/camus-shopify-0.1.0-shopify1.jar:/etc/camus:/etc/hadoop/conf '
    command += 'com.linkedin.camus.etl.kafka.CamusJob -P /u/apps/camus/shared/camus.properties"'

    project = Project('Camus')
    project.add_job('Camus', Job({'failure.emails': 'camus@shopify.pagerduty.com',
                                  'type': 'command'
                                  'command': command
    }))

    logger.info('Building zip file')
    project.build('camus.zip', True)
    logger.info('Connecting to Azkaban site')
    session = start_session(azkaban_auth['server'], azkaban_auth['user'], azkaban_auth['password'])

    logger.info('Uploading zip file')
    session.upload_project('Camus', 'camus.zip')
    logger.info('Successfully uploaded Camus zip file.')

    session.schedule_workflow('Camus', 'Camus', date='01/01/2014', time="12,01,AM,UTC", period="1h", concurrent=False)
    logger.info('Successfully scheduled Camus flow.')

if __name__ == '__main__':
    main()
